### ISSUE TITLE
rat

### ISSUE THREAD

**Issue by 1230291084308752** [FartMaster420/HybridCheats#1]
i sent the paster the link to this and then my pc just bricked i cant turn it on help please

**Comment by FartMaster420** [comment]
> i sent the paster the link to this and then my pc just bricked i cant turn it on help please

What do you mean? The loader iteslf isnt a RAT, you can check the code, it might have only crashed because the pastebin they used for password checking has been removed.
Dont know if something was us with the .dll

**Comment by FartMaster420** [comment]
Isnt it the file on your profile thats called Pc-reaper?

**Comment by 1230291084308752** [comment]
no my pc wont turn on please help please my dad is going to beat my ass

**Comment by 1230291084308752** [comment]
fuck you my pc is broken and i can never get a new one i hate you im going to ddos you

**Comment by FartMaster420** [comment]
> no my pc wont turn on please help please my dad is going to beat my ass
    Please do.

**Comment by FartMaster420** [comment]
> fuck you my pc is broken and i can never get a new one i hate you im going to ddos you

Alright

**Comment by FartMaster420** [comment]
> fuck you my pc is broken and i can never get a new one i hate you im going to ddos you

Happy to help ;)

**Comment by 1230291084308752** [comment]
i hope you die nigger you are go to hell
